In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('../data/dataseter.csv')

In [5]:
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No,Yes,NO
1,F,55,Yes,No,No,Yes,Yes,No,No,No,Yes,Yes,Yes,No,No,NO
2,F,78,No,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,Yes,YES
3,M,60,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,No,No,YES
4,F,80,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Yes,No,NO

In [8]:
databin = pd.get_dummies(data, dtype=int)

databin.head()

,AGE,GENDER_F,GENDER_M,SMOKING_No,SMOKING_Yes,YELLOW_FINGERS_No,YELLOW_FINGERS_Yes,ANXIETY_No,ANXIETY_Yes,PEER_PRESSURE_No,...,COUGHING_No,COUGHING_Yes,SHORTNESS_OF_BREATH_No,SHORTNESS_OF_BREATH_Yes,SWALLOWING_DIFFICULTY_No,SWALLOWING_DIFFICULTY_Yes,CHEST_PAIN_No,CHEST_PAIN_Yes,LUNG_CANCER_NO,LUNG_CANCER_YES
0,65,0,1,0,1,0,1,0,1,1,...,1,0,1,0,1,0,0,1,1,0
1,55,1,0,0,1,1,0,1,0,0,...,0,1,0,1,1,0,1,0,1,0
2,78,1,0,1,0,1,0,0,1,0,...,0,1,1,0,0,1,0,1,0,1
3,60,0,1,1,0,0,1,0,1,0,...,1,0,0,1,1,0,1,0,0,1
4,80,1,0,0,1,0,1,1,0,0,...,0,1,0,1,0,1,1,0,1,0

In [9]:
databin.describe()

,AGE,GENDER_F,GENDER_M,SMOKING_No,SMOKING_Yes,YELLOW_FINGERS_No,YELLOW_FINGERS_Yes,ANXIETY_No,ANXIETY_Yes,PEER_PRESSURE_No,...,COUGHING_No,COUGHING_Yes,SHORTNESS_OF_BREATH_No,SHORTNESS_OF_BREATH_Yes,SWALLOWING_DIFFICULTY_No,SWALLOWING_DIFFICULTY_Yes,CHEST_PAIN_No,CHEST_PAIN_Yes,LUNG_CANCER_NO,LUNG_CANCER_YES
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,...,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,55.169000,0.495333,0.504667,0.491000,0.509000,0.514000,0.486000,0.494000,0.506000,0.499000,...,0.510667,0.489333,0.488000,0.512000,0.489667,0.510333,0.498667,0.501333,0.494000,0.506000
std,14.723746,0.500062,0.500062,0.500002,0.500002,0.499887,0.499887,0.500047,0.500047,0.500082,...,0.499970,0.499970,0.499939,0.499939,0.499977,0.499977,0.500082,0.500082,0.500047,0.500047
min,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,55.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
75%,68.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,80.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000